# Copyright (c) 2023 Golioth, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Test firmware

on:
  pull_request:

  push:
    branches: [ main ]

jobs:
  test_build_thingy91:
    uses: ./.github/workflows/build_zephyr.yml
    with:
      ZEPHYR_SDK: 0.16.3
      BOARD: thingy91/nrf9160/ns
      ARTIFACT: false
  test_build_thingy91x:
    uses: ./.github/workflows/build_zephyr.yml
    with:
      ZEPHYR_SDK: 0.16.3
      BOARD: thingy91x/nrf9151/ns
      ARTIFACT: false
